// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ConfigSrcRedirect: typeof import('./../components/config/src/redirect.vue')['default']
    IconSrcIcon: typeof import('./../components/Icon/src/icon.vue')['default']
    IconSrcSvg: typeof import('./../components/Icon/src/svg.vue')['default']
    SettingsCompSrcColorSelect: typeof import('./../components/settingsComp/src/ColorSelect.vue')['default']
    SettingsCompSrcPageInputNum: typeof import('./../components/settingsComp/src/PageInputNum.vue')['default']
    SettingsCompSrcPageLayout: typeof import('./../components/settingsComp/src/PageLayout.vue')['default']
    SettingsCompSrcPageSelect: typeof import('./../components/settingsComp/src/PageSelect.vue')['default']
    SettingsCompSrcPageSwitch: typeof import('./../components/settingsComp/src/PageSwitch.vue')['default']
  }
}

export { }
